### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by zipzit** [jraklovits/timeKeeper#1]
Its totally not clear on how you are binding the Google Apps Script to the index.html page.  That failure makes this example incomprehensible. Is there a line of code or two missing,something that links back to your google sheet, your google calendar or your google app scripts?  A script call out in the header or something?  Clearly its not `<script src="code.gs"></script>`

I can see how to use Google Apps Scripts in Google drive, but its not clear on how to tie those to an html web page.  You just end up with `Uncaught ReferenceError: google is not defined`

Possible to leave those lines in the index.html with api keys xxxxxxxxxx hidden to protect you, buy give us a hint on how the binding works?

Or in the alternative give us a hint on how to tie things together on the markdown overview?  

Many thanks for sharing.

**Comment by jraklovits** [comment]
On google apps script, the following is documented here.
https://developers.google.com/apps-script/guides/html/templates
